# Generated by Django 5.0.6 on 2024-06-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0002_alter_chercheur_liste_projets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetrecherche',
            name='chef_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recherche.chercheur'),
        ),
    ]
