# Generated by Django 5.0.6 on 2024-06-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0003_alter_projetrecherche_chef_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='projet_associe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='recherche.projetrecherche'),
        ),
    ]
