# Generated by Django 5.0.6 on 2024-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0004_alter_publication_projet_associe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='liste_projets',
            field=models.ManyToManyField(related_name='chercheurs', to='recherche.projetrecherche'),
        ),
    ]
