# Generated by Django 5.0.6 on 2024-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0005_alter_chercheur_liste_projets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='liste_projets',
            field=models.ManyToManyField(blank=True, related_name='chercheurs', to='recherche.projetrecherche'),
        ),
    ]
